// frontend/src/views/Login.vue
<template>
    <div class="login-wrapper">
        <!-- Animated background elements -->
        <div class="bg-circle circle-1"></div>
        <div class="bg-circle circle-2"></div>
        <div class="bg-circle circle-3"></div>
        
        <div class="login-container">
            <!-- Welcome Header -->
            <div class="header">
                <div class="welcome-animation">
                    <span class="wave-emoji">👋</span>
                </div>
                <h2>CHÀO MỪNG TRỞ LẠI!</h2>
                <p class="subtitle">Hãy tiếp tục hành trình học tập của bạn nào! 🎯</p>
            </div>

            <!-- Form -->
            <form @submit.prevent="handleLogin" class="login-form">
                <!-- Phone Input -->
                <div class="form-group">
                    <label for="phone">
                        <span class="label-icon">📱</span>
                        Số điện thoại
                    </label>
                    <div class="input-wrapper">
                        <div class="input-icon-container">
                            <span class="input-emoji">📞</span>
                        </div>
                        <input 
                            id="phone"
                            v-model="form.phone"
                            type="tel"
                            placeholder="Nhập số điện thoại"
                            required
                            :disabled="loading"
                        />
                        <div class="input-underline"></div>
                    </div>
                </div>

                <!-- Password Input -->
                <div class="form-group">
                    <label for="password">
                        <span class="label-icon">🔐</span>
                        Mật khẩu
                    </label>
                    <div class="input-wrapper">
                        <div class="input-icon-container">
                            <span class="input-emoji">🔑</span>
                        </div>
                        <input 
                            id="password"
                            v-model="form.password"
                            :type="showPassword ? 'text' : 'password'"
                            placeholder="Nhập mật khẩu"
                            required
                            :disabled="loading"
                        />
                        <button 
                            type="button" 
                            class="toggle-password"
                            @click="showPassword = !showPassword"
                            :disabled="loading"
                            :title="showPassword ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'"
                        >
                            <span v-if="!showPassword">👁️</span>
                            <span v-else">🙈</span>
                        </button>
                        <div class="input-underline"></div>
                    </div>
                </div>

                <!-- Remember me & Forgot password -->
                <div class="form-options">
                    <label class="checkbox-container">
                        <input type="checkbox" v-model="rememberMe" :disabled="loading" />
                        <span class="checkmark"></span>
                        <span class="checkbox-text">Nhớ đăng nhập</span>
                    </label>
                    <router-link to="/forgetpassword" class="forgot-link">
                        Quên mật khẩu?
                    </router-link>
                </div>

                <!-- Alert Messages -->
                <transition name="slide-fade">
                    <div v-if="error" class="alert alert-error">
                        <span class="alert-emoji">😢</span>
                        <span>{{ error }}</span>
                    </div>
                </transition>

                <transition name="slide-fade">
                    <div v-if="success" class="alert alert-success">
                        <span class="alert-emoji">🎉</span>
                        <span>{{ success }}</span>
                    </div>
                </transition>

                <!-- Submit Button -->
                <button type="submit" class="submit-btn" :disabled="loading">
                    <span v-if="!loading" class="btn-content">
                        <span>Đăng nhập</span>
                        <span class="btn-icon">🚀</span>
                    </span>
                    <span v-else class="btn-content">
                        <span class="loading-spinner">⏳</span>
                        <span>Đang xử lý...</span>
                    </span>
                    <div class="btn-glow"></div>
                </button>

                <!-- Divider -->
                <!-- <div class="divider">
                    <span>HOẶC</span>
                </div> -->

                <!-- Social Login (placeholder) -->
                <!-- <div class="social-login">
                    <button type="button" class="social-btn google-btn">
                        <span class="social-icon">🔍</span>
                        <span>Google</span>
                    </button>
                    <button type="button" class="social-btn facebook-btn">
                        <span class="social-icon">👥</span>
                        <span>Facebook</span>
                    </button>
                </div> -->

                <!-- Register Link -->
                <div class="footer-text">
                    Chưa có tài khoản? 
                    <router-link to="/register" class="register-link">
                        Đăng ký ngay 🎨
                    </router-link>
                </div>
            </form>

            <!-- Motivational Quote -->
            <!-- <div class="motivation-quote">
                <span class="quote-icon">💭</span>
                <p>"Học hành là kho báu sẽ theo bạn khắp mọi nơi"</p>
            </div> -->
        </div>
    </div>
</template>

<script setup>
import { reactive, ref } from "vue";
import http from "../api/http";
import TeacherHomePage from "./Teacher/HomePage.vue";   
import { useRouter } from "vue-router";

const router = useRouter();

const loading = ref(false);
const error = ref("");
const success = ref("");
const showPassword = ref(false);
const rememberMe = ref(false);

const form = reactive({
    phone: "",
    password: ""
});

const handleLogin = async () => {
    error.value = "";
    success.value = "";

    if (!form.phone || !form.password) {
        error.value = "Vui lòng nhập đầy đủ thông tin";
        return;
    }

    loading.value = true;

    try {
        const response = await http.post("/api/login", {
            phone: form.phone,
            password: form.password
        });

        const { access_token, user } = response.data.data;

        if (!access_token || !user?.role) {
            throw new Error("Dữ liệu đăng nhập không hợp lệ");
        }

        // Lưu token
        localStorage.setItem("token", access_token);

        // Điều hướng theo role
        if (user.role === "student") {
            router.push("/students/homepage");
        } 
        else if (user.role === "teacher") {
            router.push("/teacher/homepage");
        } 
        else if (user.role === "admin") {
            router.push("/admin/homepage");
        } 
        else {
            throw new Error("Vai trò người dùng không xác định");
        }

        // ✅ CHỈ set success khi mọi thứ OK
        success.value = "Đăng nhập thành công! 🎉";

    } catch (err) {
        console.error(err);
        error.value =
            err.response?.data?.message ||
            err.message ||
            "Đăng nhập thất bại. Vui lòng kiểm tra lại thông tin.";
    } finally {
        loading.value = false;
    }
};

</script>

<style scoped>
* {
    box-sizing: border-box;
}

.login-wrapper {
    min-height: calc(100vh - 200px);
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 2rem 1.5rem;
    position: relative;
    overflow: hidden;
}

/* Animated Background */
.bg-circle {
    position: absolute;
    border-radius: 50%;
    filter: blur(60px);
    opacity: 0.3;
    animation: float-rotate 20s ease-in-out infinite;
}

.circle-1 {
    width: 300px;
    height: 300px;
    background: linear-gradient(135deg, #FF6B9D, #FFE66D);
    top: -100px;
    left: -100px;
    animation-delay: 0s;
}

.circle-2 {
    width: 250px;
    height: 250px;
    background: linear-gradient(135deg, #4ECDC4, #667eea);
    bottom: -80px;
    right: -80px;
    animation-delay: 7s;
}

.circle-3 {
    width: 200px;
    height: 200px;
    background: linear-gradient(135deg, #FFE66D, #FF6B9D);
    top: 50%;
    right: 10%;
    animation-delay: 14s;
}

@keyframes float-rotate {
    0%, 100% {
        transform: translate(0, 0) rotate(0deg);
    }
    33% {
        transform: translate(30px, -30px) rotate(120deg);
    }
    66% {
        transform: translate(-20px, 20px) rotate(240deg);
    }
}

.login-container {
    position: relative;
    z-index: 1;
    width: 100%;
    max-width: 450px;
    background: rgba(255, 255, 255, 0.95);
    backdrop-filter: blur(20px);
    border-radius: 28px;
    box-shadow: 0 25px 70px rgba(0, 0, 0, 0.15);
    padding: 1.5rem 2rem;
    animation: slideUp 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.275);
    border: 2px solid rgba(255, 255, 255, 0.8);
}

@keyframes slideUp {
    from {
        opacity: 0;
        transform: translateY(40px) scale(0.9);
    }
    to {
        opacity: 1;
        transform: translateY(0) scale(1);
    }
}

/* Header */
.header {
    text-align: center;
    margin-bottom: 2rem;
}

.welcome-animation {
    margin-bottom: 1rem;
}

.wave-emoji {
    font-size: 4rem;
    display: inline-block;
    animation: wave 1.5s ease-in-out infinite;
    transform-origin: 70% 70%;
}

@keyframes wave {
    0%, 100% {
        transform: rotate(0deg);
    }
    10%, 30%, 50%, 70%, 90% {
        transform: rotate(14deg);
    }
    20%, 40%, 60%, 80% {
        transform: rotate(-8deg);
    }
}

.header h2 {
    margin: 0 0 0.75rem;
    font-size: 1.875rem;
    font-weight: 900;
    background: linear-gradient(135deg, #667eea, #FF6B9D);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.subtitle {
    margin: 0;
    color: #718096;
    font-size: 0.9375rem;
    font-weight: 600;
}

/* Form */
.login-form {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
}

.form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
}

.form-group label {
    font-size: 0.9375rem;
    font-weight: 700;
    color: #2d3748;
    display: flex;
    align-items: center;
    gap: 0.5rem;
}

.label-icon {
    font-size: 1.25rem;
}

.input-wrapper {
    position: relative;
    display: flex;
    align-items: center;
}

.input-icon-container {
    position: absolute;
    left: 1rem;
    z-index: 1;
}

.input-emoji {
    font-size: 1.5rem;
}

.input-wrapper input {
    width: 100%;
    padding: 1rem 1rem 1rem 3.5rem;
    border: 3px solid #e2e8f0;
    border-radius: 16px;
    font-size: 1rem;
    transition: all 0.3s ease;
    background: white;
    font-weight: 500;
}

.input-wrapper input:focus {
    outline: none;
    border-color: #667eea;
    transform: translateY(-2px);
    box-shadow: 0 4px 15px rgba(102, 126, 234, 0.2);
}

.input-wrapper input:focus ~ .input-underline {
    transform: scaleX(1);
}

.input-underline {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 3px;
    background: linear-gradient(90deg, #FF6B9D, #FFE66D, #4ECDC4);
    border-radius: 0 0 16px 16px;
    transform: scaleX(0);
    transform-origin: left;
    transition: transform 0.3s ease;
}

.input-wrapper input:disabled {
    background: #edf2f7;
    cursor: not-allowed;
    opacity: 0.6;
}

.toggle-password {
    position: absolute;
    right: 1rem;
    background: none;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    padding: 0.25rem;
    transition: transform 0.2s ease;
    z-index: 1;
}

.toggle-password:hover {
    transform: scale(1.2);
}

.toggle-password:disabled {
    cursor: not-allowed;
    opacity: 0.5;
}

/* Form Options */
.form-options {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.875rem;
    flex-wrap: wrap;
    gap: 0.5rem;
}

.checkbox-container {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    cursor: pointer;
    position: relative;
    padding-left: 2rem;
}

.checkbox-container input {
    position: absolute;
    opacity: 0;
    cursor: pointer;
}

.checkmark {
    position: absolute;
    left: 0;
    height: 20px;
    width: 20px;
    background-color: #e2e8f0;
    border-radius: 6px;
    transition: all 0.3s ease;
}

.checkbox-container:hover .checkmark {
    background-color: #cbd5e0;
}

.checkbox-container input:checked ~ .checkmark {
    background: linear-gradient(135deg, #667eea, #764ba2);
}

.checkmark:after {
    content: "✓";
    position: absolute;
    display: none;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    color: white;
    font-weight: bold;
    font-size: 14px;
}

.checkbox-container input:checked ~ .checkmark:after {
    display: block;
}

.checkbox-text {
    color: #2d3748;
    font-weight: 600;
}

.forgot-link {
    color: #667eea;
    text-decoration: none;
    font-weight: 700;
    transition: all 0.2s ease;
}

.forgot-link:hover {
    color: #FF6B9D;
}

/* Alerts */
.alert {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem 1.25rem;
    border-radius: 16px;
    font-size: 0.9375rem;
    font-weight: 600;
}

.alert-emoji {
    font-size: 1.5rem;
}

.alert-error {
    background: linear-gradient(135deg, #fff5f5, #ffe5e5);
    color: #c53030;
    border: 2px solid #feb2b2;
}

.alert-success {
    background: linear-gradient(135deg, #f0fff4, #dcffe4);
    color: #2f855a;
    border: 2px solid #9ae6b4;
}

.slide-fade-enter-active {
    animation: slideInDown 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

.slide-fade-leave-active {
    animation: slideOutUp 0.3s ease;
}

@keyframes slideInDown {
    from {
        opacity: 0;
        transform: translateY(-20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

@keyframes slideOutUp {
    to {
        opacity: 0;
        transform: translateY(-20px);
    }
}

/* Submit Button */
.submit-btn {
    position: relative;
    width: 100%;
    padding: 1.25rem;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    border: none;
    border-radius: 50px;
    font-size: 1.125rem;
    font-weight: 800;
    cursor: pointer;
    transition: all 0.4s ease;
    margin-top: 0.5rem;
    text-transform: uppercase;
    letter-spacing: 1px;
    overflow: hidden;
}

.submit-btn::before {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 0;
    height: 0;
    border-radius: 50%;
    background: rgba(255, 255, 255, 0.3);
    transform: translate(-50%, -50%);
    transition: width 0.6s, height 0.6s;
}

.submit-btn:hover::before {
    width: 300px;
    height: 300px;
}

.submit-btn:hover:not(:disabled) {
    transform: translateY(-3px);
    box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4);
}

.submit-btn:active:not(:disabled) {
    transform: translateY(-1px);
}

.submit-btn:disabled {
    opacity: 0.7;
    cursor: not-allowed;
}

.btn-content {
    position: relative;
    z-index: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
}

.btn-icon {
    font-size: 1.25rem;
    animation: bounce 1s ease-in-out infinite;
}

.loading-spinner {
    font-size: 1.25rem;
    animation: spin 1s linear infinite;
}

@keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
}

/* Divider */
.divider {
    position: relative;
    text-align: center;
    margin: 1.5rem 0;
}

.divider::before,
.divider::after {
    content: '';
    position: absolute;
    top: 50%;
    width: 40%;
    height: 2px;
    background: linear-gradient(90deg, transparent, #e2e8f0, transparent);
}

.divider::before {
    left: 0;
}

.divider::after {
    right: 0;
}

.divider span {
    position: relative;
    padding: 0 1rem;
    background: rgba(255, 255, 255, 0.95);
    color: #a0aec0;
    font-size: 0.75rem;
    font-weight: 700;
}

/* Social Login */
.social-login {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
}

.social-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.875rem;
    border-radius: 12px;
    border: 2px solid #e2e8f0;
    background: white;
    font-weight: 700;
    font-size: 0.9375rem;
    cursor: pointer;
    transition: all 0.3s ease;
}

.social-icon {
    font-size: 1.25rem;
}

.google-btn:hover {
    border-color: #FF6B9D;
    background: #fff5f8;
    transform: translateY(-2px);
}

.facebook-btn:hover {
    border-color: #4ECDC4;
    background: #f0fdfa;
    transform: translateY(-2px);
}

/* Footer */
.footer-text {
    text-align: center;
    margin-top: 1.5rem;
    color: #718096;
    font-size: 0.9375rem;
    font-weight: 600;
}

.register-link {
    color: #667eea;
    text-decoration: none;
    font-weight: 800;
    transition: all 0.2s ease;
}

.register-link:hover {
    color: #FF6B9D;
}

/* Motivation Quote */
.motivation-quote {
    margin-top: 2rem;
    padding: 1rem;
    background: linear-gradient(135deg, rgba(255, 230, 109, 0.2), rgba(78, 205, 196, 0.2));
    border-radius: 16px;
    border: 2px dashed #FFE66D;
    text-align: center;
}

.quote-icon {
    font-size: 1.5rem;
    display: block;
    margin-bottom: 0.5rem;
}

.motivation-quote p {
    margin: 0;
    font-size: 0.875rem;
    color: #2d3748;
    font-weight: 600;
    font-style: italic;
}

/* Responsive */
@media (max-width: 480px) {
    .login-wrapper {
        padding: 1.5rem 1rem;
    }

    .login-container {
        padding: 2rem 1.5rem;
    }

    .header h2 {
        font-size: 1.625rem;
    }

    .wave-emoji {
        font-size: 3rem;
    }

    .login-form {
        gap: 1.25rem;
    }

    .social-login {
        grid-template-columns: 1fr;
    }

    .form-options {
        flex-direction: column;
        align-items: flex-start;
    }
}

@media (min-width: 481px) and (max-width: 768px) {
    .login-container {
        max-width: 480px;
        padding: 2.75rem 2.25rem;
    }
}
</style>

// frontend/src/app/features/auth/Login.tsx
import { useState } from "react";
import { Link, useNavigate } from "react-router";
import {
  Mail,
  Lock,
  Eye,
  EyeOff,
  ArrowRight,
  CheckCircle2,
  Sparkles,
  BookOpen,
  Users,
  Award,
  TrendingUp,
  Globe,
  Zap,
  Shield,
} from "lucide-react";

export function Login() {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [rememberMe, setRememberMe] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    // Simulate login
    setTimeout(() => {
      setIsLoading(false);
      navigate("/giao-vien");
    }, 1500);
  };

  const features = [
    { icon: BookOpen, text: "Quản lý đề thi thông minh", color: "text-blue-400" },
    { icon: Users, text: "Theo dõi tiến độ học sinh", color: "text-green-400" },
    { icon: Award, text: "Chấm điểm tự động & nhanh chóng", color: "text-purple-400" },
    { icon: TrendingUp, text: "Phân tích & thống kê chi tiết", color: "text-orange-400" },
  ];

  const stats = [
    { value: "50K+", label: "Giáo viên", icon: Users },
    { value: "500K+", label: "Học sinh", icon: Globe },
    { value: "1M+", label: "Bài kiểm tra", icon: BookOpen },
    { value: "99%", label: "Hài lòng", icon: Award },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-purple-900 relative overflow-hidden flex items-center justify-center p-4">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        {/* Gradient Orbs */}
        <div className="absolute top-0 left-0 w-96 h-96 bg-blue-500/30 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-0 right-0 w-96 h-96 bg-purple-500/30 rounded-full blur-3xl animate-pulse delay-1000" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-pink-500/20 rounded-full blur-3xl animate-pulse delay-500" />
        
        {/* Floating Shapes */}
        <div className="absolute top-20 left-20 w-20 h-20 border-2 border-white/10 rounded-lg rotate-12 animate-float" />
        <div className="absolute top-40 right-40 w-16 h-16 border-2 border-white/10 rounded-full animate-float delay-300" />
        <div className="absolute bottom-40 left-40 w-24 h-24 border-2 border-white/10 rounded-lg -rotate-12 animate-float delay-700" />
        
        {/* Grid Pattern */}
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:50px_50px]" />
      </div>

      {/* Main Content */}
      <div className="relative w-full max-w-7xl mx-auto">
        <div className="grid lg:grid-cols-2 gap-8 items-center">
          {/* Left Side - Branding & Features */}
          <div className="hidden lg:block space-y-8 text-white">
            {/* Logo & Title */}
            <div className="space-y-6">
              <div className="inline-flex items-center gap-3 px-4 py-2 bg-white/10 backdrop-blur-md rounded-full border border-white/20">
                <div className="w-8 h-8 bg-gradient-to-br from-blue-400 to-purple-400 rounded-full flex items-center justify-center">
                  <Sparkles className="w-5 h-5 text-white" />
                </div>
                <span className="font-bold text-lg">NamThu Education</span>
              </div>
              
              <h1 className="text-5xl font-bold leading-tight">
                <span className="bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
                  Teacher Dashboard
                </span>
                <br />
                <span className="text-white">Nền tảng quản lý</span>
                <br />
                <span className="text-white">giáo dục hiện đại</span>
              </h1>
              
              <p className="text-xl text-blue-200 leading-relaxed">
                Công cụ toàn diện giúp giáo viên tiếng Anh tạo đề thi, quản lý lớp học và theo dõi tiến độ học sinh một cách hiệu quả.
              </p>
            </div>

            {/* Features */}
            <div className="space-y-4">
              {features.map((feature, index) => (
                <div
                  key={index}
                  className="flex items-center gap-4 p-4 bg-white/5 backdrop-blur-sm rounded-xl border border-white/10 hover:bg-white/10 transition-all duration-300 group"
                  style={{ animationDelay: `${index * 100}ms` }}
                >
                  <div className={`w-12 h-12 rounded-xl bg-white/10 flex items-center justify-center group-hover:scale-110 transition-transform`}>
                    <feature.icon className={`w-6 h-6 ${feature.color}`} />
                  </div>
                  <p className="text-lg font-medium text-white/90">{feature.text}</p>
                </div>
              ))}
            </div>

            {/* Stats */}
            <div className="grid grid-cols-4 gap-4 pt-8 border-t border-white/10">
              {stats.map((stat, index) => (
                <div key={index} className="text-center">
                  <div className="flex justify-center mb-2">
                    <stat.icon className="w-5 h-5 text-blue-400" />
                  </div>
                  <p className="text-2xl font-bold text-white mb-1">{stat.value}</p>
                  <p className="text-xs text-blue-200">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Right Side - Login Form */}
          <div className="w-full">
            <div className="bg-white/10 backdrop-blur-xl rounded-3xl border border-white/20 shadow-2xl p-8 lg:p-12">
              {/* Mobile Logo */}
              <div className="lg:hidden flex justify-center mb-8">
                <div className="inline-flex items-center gap-3 px-4 py-2 bg-white/10 backdrop-blur-md rounded-full border border-white/20">
                  <div className="w-8 h-8 bg-gradient-to-br from-blue-400 to-purple-400 rounded-full flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-white" />
                  </div>
                  <span className="font-bold text-lg text-white">NamThu Education</span>
                </div>
              </div>

              {/* Form Header */}
              <div className="text-center mb-8">
                <h2 className="text-3xl font-bold text-white mb-3">Chào mừng trở lại! 👋</h2>
                <p className="text-blue-200">Đăng nhập để tiếp tục với Teacher Dashboard</p>
              </div>

              {/* Social Login */}
              <div className="grid grid-cols-2 gap-4 mb-8">
                <button className="flex items-center justify-center gap-3 px-4 py-3 bg-white/10 hover:bg-white/20 backdrop-blur-sm rounded-xl border border-white/20 transition-all duration-300 group">
                  <svg className="w-5 h-5" viewBox="0 0 24 24">
                    <path
                      fill="currentColor"
                      className="text-white"
                      d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                    />
                    <path
                      fill="currentColor"
                      className="text-blue-400"
                      d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                    />
                    <path
                      fill="currentColor"
                      className="text-yellow-400"
                      d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                    />
                    <path
                      fill="currentColor"
                      className="text-green-400"
                      d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                    />
                  </svg>
                  <span className="font-semibold text-white">Google</span>
                </button>
                <button className="flex items-center justify-center gap-3 px-4 py-3 bg-white/10 hover:bg-white/20 backdrop-blur-sm rounded-xl border border-white/20 transition-all duration-300 group">
                  <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M12 2C6.477 2 2 6.477 2 12c0 4.42 2.87 8.17 6.84 9.5.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34-.46-1.16-1.11-1.47-1.11-1.47-.91-.62.07-.6.07-.6 1 .07 1.53 1.03 1.53 1.03.87 1.52 2.34 1.07 2.91.83.09-.65.35-1.09.63-1.34-2.22-.25-4.55-1.11-4.55-4.92 0-1.11.38-2 1.03-2.71-.1-.25-.45-1.29.1-2.64 0 0 .84-.27 2.75 1.02.79-.22 1.65-.33 2.5-.33.85 0 1.71.11 2.5.33 1.91-1.29 2.75-1.02 2.75-1.02.55 1.35.2 2.39.1 2.64.65.71 1.03 1.6 1.03 2.71 0 3.82-2.34 4.66-4.57 4.91.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0012 2z" />
                  </svg>
                  <span className="font-semibold text-white">GitHub</span>
                </button>
              </div>

              {/* Divider */}
              <div className="relative mb-8">
                <div className="absolute inset-0 flex items-center">
                  <div className="w-full border-t border-white/20" />
                </div>
                <div className="relative flex justify-center text-sm">
                  <span className="px-4 bg-white/10 backdrop-blur-sm text-blue-200 rounded-full">
                    Hoặc đăng nhập bằng email
                  </span>
                </div>
              </div>

              {/* Login Form */}
              <form onSubmit={handleSubmit} className="space-y-6">
                {/* Email Input */}
                <div className="space-y-2">
                  <label className="block text-sm font-semibold text-white">Email</label>
                  <div className="relative">
                    <Mail className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-blue-300" />
                    <input
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      placeholder="teacher@namthu.edu.vn"
                      required
                      className="w-full pl-12 pr-4 py-4 bg-white/10 backdrop-blur-sm border border-white/20 rounded-xl text-white placeholder-blue-300/50 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition-all"
                    />
                  </div>
                </div>

                {/* Password Input */}
                <div className="space-y-2">
                  <label className="block text-sm font-semibold text-white">Mật khẩu</label>
                  <div className="relative">
                    <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-blue-300" />
                    <input
                      type={showPassword ? "text" : "password"}
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      placeholder="••••••••"
                      required
                      className="w-full pl-12 pr-12 py-4 bg-white/10 backdrop-blur-sm border border-white/20 rounded-xl text-white placeholder-blue-300/50 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition-all"
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-4 top-1/2 -translate-y-1/2 text-blue-300 hover:text-white transition-colors"
                    >
                      {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                    </button>
                  </div>
                </div>

                {/* Remember Me & Forgot Password */}
                <div className="flex items-center justify-between">
                  <label className="flex items-center gap-2 cursor-pointer group">
                    <input
                      type="checkbox"
                      checked={rememberMe}
                      onChange={(e) => setRememberMe(e.target.checked)}
                      className="w-4 h-4 rounded border-white/20 bg-white/10 text-blue-500 focus:ring-2 focus:ring-blue-400 focus:ring-offset-0"
                    />
                    <span className="text-sm text-blue-200 group-hover:text-white transition-colors">
                      Ghi nhớ đăng nhập
                    </span>
                  </label>
                  <Link
                    to="/forgot-password"
                    className="text-sm text-blue-300 hover:text-white transition-colors font-medium"
                  >
                    Quên mật khẩu?
                  </Link>
                </div>

                {/* Submit Button */}
                <button
                  type="submit"
                  disabled={isLoading}
                  className="w-full py-4 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 hover:from-blue-600 hover:via-purple-600 hover:to-pink-600 text-white font-bold rounded-xl shadow-2xl shadow-purple-500/50 hover:shadow-purple-500/70 transition-all duration-300 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed group"
                >
                  {isLoading ? (
                    <>
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      <span>Đang đăng nhập...</span>
                    </>
                  ) : (
                    <>
                      <span>Đăng nhập</span>
                      <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                    </>
                  )}
                </button>
              </form>

              {/* Sign Up Link */}
              <div className="mt-8 text-center">
                <p className="text-blue-200">
                  Chưa có tài khoản?{" "}
                  <Link
                    to="/register"
                    className="text-white font-bold hover:text-blue-300 transition-colors inline-flex items-center gap-1"
                  >
                    Đăng ký ngay
                    <Sparkles className="w-4 h-4" />
                  </Link>
                </p>
              </div>

              {/* Security Badge */}
              <div className="mt-8 pt-8 border-t border-white/10">
                <div className="flex items-center justify-center gap-2 text-sm text-blue-200">
                  <Shield className="w-4 h-4 text-green-400" />
                  <span>Bảo mật với mã hóa SSL 256-bit</span>
                </div>
              </div>
            </div>

            {/* Bottom Note */}
            <div className="mt-6 text-center text-sm text-blue-200">
              <p>
                Bằng việc đăng nhập, bạn đồng ý với{" "}
                <Link to="/terms" className="text-white hover:underline">
                  Điều khoản sử dụng
                </Link>{" "}
                và{" "}
                <Link to="/privacy" className="text-white hover:underline">
                  Chính sách bảo mật
                </Link>
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Floating Particles Effect */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        {[...Array(20)].map((_, i) => (
          <div
            key={i}
            className="absolute w-1 h-1 bg-white/30 rounded-full animate-float-slow"
            style={{
              left: `${Math.random() * 100}%`,
              top: `${Math.random() * 100}%`,
              animationDelay: `${Math.random() * 5}s`,
              animationDuration: `${5 + Math.random() * 10}s`,
            }}
          />
        ))}
      </div>
    </div>
  );
}
